import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices, DefaultTokenBuilder
} from 'langium';
import { SlideDeckMLGeneratedModule, SlideDeckMlGeneratedSharedModule } from './generated/module';

/**
 * Custom TokenBuilder that prioritizes specific terminals
 */
class SlideDeckMLTokenBuilder extends DefaultTokenBuilder {
    protected override buildTerminalTokens(grammar: any) {
        const tokens = super.buildTerminalTokens(grammar);
        
        // Find the paragraph text token and mark it as longer_alt
        const paragraphToken = tokens.find((t: any) => t.name === 'PARAGRAPH_TEXT');
        if (paragraphToken) {
            // Mark all other tokens as having higher priority than PARAGRAPH_TEXT
            paragraphToken.LONGER_ALT = tokens.filter((t: any) => 
                t.name === 'HEADER_LEVEL' ||
                t.name === 'LIST_MARKER' ||
                t.name === '>' ||
                t.name === 'MEDIA_LINE' ||
                t.name === 'CODE_BLOCK' ||
                t.name === 'STYLE_DELIMITER' ||
                t.name === 'STYLE_ATTRS' ||
                t.name === 'SLIDE_SEPARATOR' ||
                t.name === 'TEMPLATE_SEPARATOR' ||
                // Include keyword tokens for metadata
                t.name === '{' || t.name === '}' || t.name === ':' ||
                t.name === 'author' || t.name === 'title'
            );
        }
        
        return tokens;
    }
}

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SlideDeckMlAddedServices = {
    validation: {

    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SlideDeckMlServices = LangiumServices & SlideDeckMlAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SlideDeckMLModule: Module<SlideDeckMlServices, PartialLangiumServices & SlideDeckMlAddedServices> = {
    validation: {},
    parser: {
        TokenBuilder: () => new SlideDeckMLTokenBuilder()
    }
};


/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSlideDeckMlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SlideDeckMl: SlideDeckMlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SlideDeckMlGeneratedSharedModule
    );
    const SlideDeckMl = inject(
        createDefaultModule({ shared }),
        SlideDeckMLGeneratedModule,
        SlideDeckMLModule
    );
    shared.ServiceRegistry.register(SlideDeckMl);
    return { shared, SlideDeckMl };
}